-- Migration: Personnel-User Account Sync & Employment Type Normalization
-- Date: 2026-02-06
-- Description:
--   1. Convert all 'Contract of Service' and 'COS / JO' employment types to 'COS' in personnels table
--   2. Reset ALL existing user_accounts passwords to 'dogh_2026' (bcrypt hash)
--   3. Create user_accounts for all personnels that don't have one yet (default password: dogh_2026)

-- ============================================================
-- STEP 1: Normalize employment_type in personnels table
-- ============================================================
UPDATE personnels SET employment_type = 'COS' WHERE employment_type = 'Contract of Service';
UPDATE personnels SET employment_type = 'COS' WHERE employment_type = 'COS / JO';

-- ============================================================
-- STEP 2: Reset ALL existing user passwords to 'dogh_2026'
-- BCrypt hash of 'dogh_2026': $2y$10$YW5vdGhlcmhhc2hkb2doMOKAi3JhbmRvbXNhbHRzdHJpbmc
-- NOTE: You MUST generate the actual hash via PHP. Run the helper script below instead.
-- ============================================================
-- This will be handled by the PHP migration script below since bcrypt hashes
-- need to be generated by PHP's password_hash() function.

-- ============================================================
-- STEP 3: Create user_accounts for personnels without accounts
-- ============================================================
-- This will also be handled by the PHP migration script since we need
-- password_hash() and username uniqueness logic.
